AllEvent/urls.py
from django.urls import path

from .views import Events, details, confirm
app_name= 'event'
urlpatterns = [
    path('', Events, name='event'),
    path('details/<event>/',details, name='details'),
    path('confirm/<event>/',confirm, name='confirm')
    
]

Home/urls.py
from django.urls import path

from .views import homePageView

urlpatterns = [
    path('', homePageView, name='home')
]

News/urls.py
from django.urls import path
from .views import News
app_name = 'news'

urlpatterns = [
	path('', News, name='news'),
]

RegisMember/urls.py
from django.urls import path
from . import views

app_name= 'regismember'
urlpatterns = [
    path('', views.RegisMemberView, name='regismember'),
    path('confirmationpage/', views.ConfirmationPageView, name='confirmationpage'),
    path('listmember/', views.listmember, name='listmember'),
    path('logout/', views.logout_view, name='logout'),
    path('validate/', views.checker, name='validate_mail'),
    path('loginPass/', views.loginPass, name='loginPass'),
    path('holdUp/', views.transition, name='transition'),
    path('confirmed/', views.bookconfirm, name='bookconfirm'),
]

TP1/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('event/', include('AllEvent.urls',namespace="event")),
    path('regismember/', include('RegisMember.urls', namespace="regismember")),
    path('bookform/', include('formBookEvent.urls',namespace="bookform")),
    path('news/', include('News.urls',namespace="news")),
    path('about/', include('About.urls', namespace="about")),
    path('', include('Home.urls')),
    path('bookformMember/', include('bookasMember.urls', namespace='bookformMember')),
	path('profileEvent/', include('ListEvent.urls', namespace='eventList'))
]

Home/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def homePageView(request):
    return render(request,'tes.html')

Home/templates/tes.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
</head>

<div class="container">
	<div class="row">
		<div class="col-md-6 position">
			<div class="main-text">
				<article>Get in</article>
				<article>The Now!</article>
			</div>
			<div class="roundedrec">
				<div class="insiderec">
					<div class="explanation">
						<article>a website for those who are looking for events and news</article>
						<br>
						<article class="developer">Developer</article>
						<ul class="developer">
							<li>Ali Yusuf (1706044061)</li>
							<li>Irene Pixelyne (1706984631)</li>
							<li>Nabilla Yuli Shafira (1706984682)</li>
							<li>Rahmadian Tio Pratama (1706044074)</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 text-center">
			<!-- {% if user.is_authenticated %}
				
			{% else %}
			<div class="join">
					<a href="{% url 'regismember:regismember' %}">
						<img src="{% static "photos/join.png" %}" class="join">
					</a>
			</div>
			{% endif %} -->
			
			<div class="head-text">
				<div class="poster-position">
					<article>Discover Event</article>
					<br>
					<img src="{% static "photos/posters.png" %}" class="poster-size">
					<a href="{% url 'event:event' %}">
						<p class="see-all">see all ></p>
					</a>
				</div>
				<div class="news-position">
					<article>Discover News</article>
					<br>
					<img src="{% static "photos/news.png" %}" class="news-size">
					<a href="{% url 'news:news' %}">
						<p class="see-all">see all ></p>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}