RegisMember/urls.py
from django.urls import path
from . import views

app_name= 'regismember'
urlpatterns = [
    path('', views.RegisMemberView, name='regismember'),
    path('confirmationpage/', views.ConfirmationPageView, name='confirmationpage'),
    path('listmember/', views.listmember, name='listmember'),
    path('logout/', views.logout_view, name='logout'),
    path('validate/', views.checker, name='validate_mail'),
    path('loginPass/', views.loginPass, name='loginPass'),
    path('holdUp/', views.transition, name='transition'),
    path('confirmed/', views.bookconfirm, name='bookconfirm'),
]

TP1/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('event/', include('AllEvent.urls',namespace="event")),
    path('regismember/', include('RegisMember.urls', namespace="regismember")),
    path('bookform/', include('formBookEvent.urls',namespace="bookform")),
    path('news/', include('News.urls',namespace="news")),
    path('about/', include('About.urls', namespace="about")),
    path('', include('Home.urls')),
    path('bookformMember/', include('bookasMember.urls', namespace='bookformMember')),
	path('profileEvent/', include('ListEvent.urls', namespace='eventList'))
]

RegisMember/models.py
from django.db import models
from datetime import datetime, date
from django.contrib.auth.models import AbstractUser


# Create your models here.

class RegisMember(AbstractUser):
    fullname = models.CharField(max_length=255, null=True, blank=True)
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(max_length=255)
    date = models.DateField(null=True, blank=True)
    password = models.CharField(max_length=255)
    address = models.TextField(max_length=300, null=True, blank=True)
    

RegisMember/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import RegisMember
from django.core.exceptions import ValidationError

invalid_message={
    'required' : 'Please fill out this field',
    'invalid' : 'Please fill out with valid Input',
}

fullname_attrs={
    'type' : 'text',
    'class' : 'todo-form-input',
    'placeholder' : 'Please enter your fullname',
}

username_attrs={
    'type' : 'text',
    'class' : 'todo-form-input',
    'placeholder' : 'Create your username',
}

email_attrs={
    'type' : 'text',
    'class' : 'todo-form-input',
    'placeholder' : 'Please enter a valid email address',
}

address_attrs={
    'type' : 'text',
    'class' : 'todo-form-input',
    'placeholder' : 'Please enter your address',
    'size' : '100',
}

password_attrs={
    'type' : 'password',
    'class' : 'todo-form-input',
    'placeholder' : 'Password should be a combination of Alphabets and Numbers',
}

class RegisMemberForm(UserCreationForm):
    fullname = forms.CharField(label = "FULLNAME", required = True, max_length=60, widget=forms.TextInput(attrs = fullname_attrs))
    username = forms.CharField(label= "USERNAME", required = True, max_length=30, widget=forms.TextInput(attrs = username_attrs))
    email = forms.EmailField(label= "EMAIL", required = True, max_length=30, widget=forms.TextInput(attrs = email_attrs))
    date = forms.DateField(label = "DATE OF BIRTH", required = True, widget=forms.DateInput(attrs={'type':'date'}))
    address = forms.CharField(label = "ADDRESS", required = True, max_length=300, widget=forms.Textarea(attrs = address_attrs))

    class Meta:
        model = RegisMember
        fields = ('fullname', 'username', 'email', 'date', 'address', )
        
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = RegisMember.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username
 
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = RegisMember.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email
 
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
 
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2



        

RegisMember/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import RegisMemberForm
from .models import RegisMember
from django.shortcuts import redirect
from django.db import IntegrityError
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login, authenticate
from django.http import JsonResponse
from AllEvent.models import Event

# Create your views here.

def listmember(request):
    response = {}
    members = RegisMember.objects.all()
    response = {
        "members" : members
    }
    return render(request, 'listmember.html', response)

def transition(request):
    response={}
    return render(request, 'transition.html', response)

@csrf_exempt
def bookconfirm(request):
    response={}
    user = request.user
    
    events= user.event_set.all().last()
    response['target'] = events
    return render(request, 'bookconfirm.html', response)

def logout_view(request):
    logout(request)
    print("EE")
    return redirect('home')

def checker(request):
    username = request.POST.get('username', None)
    data = {
        'is_taken': RegisMember.objects.filter(username=username).exists()
    }
    return JsonResponse(data)

def loginPass(request):
    username = request.POST.get('username', None)
    password = request.POST.get('password', None)
    user=authenticate(username=username, password=password)
    bisa= "tidak"
    if type(user)== RegisMember:
        bisa = "iya"
    data={
        "bisa": bisa
        }
    return JsonResponse(data)
    

def RegisMemberView(request):
    if request.method == 'POST':
        form = RegisMemberForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = RegisMemberForm()
    return render(request, 'regismember.html', {'form': form})

def ConfirmationPageView(request):
    response={}
    return render(request, 'confirmationpage.html', response)


##    form = RegisMemberForm(request.POST or None)
##    members = RegisMember.objects.all()
##    response = {
##        "members" : members
##    }
##    response['form'] = form
##
##    try:
##        if(request.method == "POST" ):
##            fullname = request.POST.get("fullname")
##            username = request.POST.get("username")
##            email = request.POST.get("email")
##            date = request.POST.get("date")
##            password = request.POST.get("password")
##            address= request.POST.get("address")
##            RegisMember.objects.create(fullname=fullname, username=username, email=email, date=date, password=password, address=address)
##            user = authenticate(username=username, password=password)
##            login(request, user)
##            return redirect('regismember:confirmationpage')
##        else:
##            print("RRRRRRR")
##            return render(request, 'regismember.html', response)
##
##    except IntegrityError as e:
##        print("RRRRRRRa")
##        return render(request, 'regismember.html', response)







            
    

RegisMember/templates/bookconfirm.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/bookEvent.css' %}" type="text/css">
</head>

<body>
    <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="text3">
                            <h1 class="text4">You are registered for {{target}}</h1><br>
                                Booking details : <br>
                                Date : {{target.date}} <br>
                                Location : {{target.place}}<br>
                                Price : {{target.price}}<br><br>
                                {{target.description}}<br><br>
                            <a>
                                <p class="thick text5">Thankyou! 
                                    <br> Your booking has been confirmed
                                    <p id="countmesg"></p>
                                </p>
                            </a>      
                        </div>
                    </div>
            </div>
        </div>
</body>

<script type="text/javascript">
    $(document).ready(function() {
    var delay = 10;
    var url = "{% url 'home' %}";
    function countdown() {
        setTimeout(countdown, 1000) ;
        $('#countmesg').html("Redirecting in "  + delay  + " seconds.");
        delay --;
        if (delay < 0 ) {
            window.location = url ;
            delay = 0 ;
        }
    }
    countdown() ;
    });
</script>

{% endblock %}

RegisMember/templates/confirmationpage.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/regisMember.css' %}" type="text/css">
</head>

<body>
    <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="text-sign">
                            <h1 class="signed-in">You are signed in!</h1>
                            <a href="{% url 'home' %}">
                                <p class="thick text-brown">Get to know what's <strong> trending</strong></p>
                                <br>
                                <a href="{% url 'regismember:listmember' %}">
                                    <input type="submit" value="PEOPLE ON TRENDING" action="{% url 'regismember:listmember' %}">
                                </a>
                            </a>
                        </div>
                    </div>
            </div>
        </div>

</body>


{% endblock %}

RegisMember/templates/listmember.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/regisMember.css' %}" type="text/css">
</head>


<div class="container">
    <div class="row">
        <div class="col-md-4 text-center list">
            <div class="roundedrec">
                <div class="insiderec">
                        <p class="signed-in">Hello!</p>
                    <table style="width:100%">
                        {% if members %}
                            {% for x in members %}
                            <tr>
                                <td class="isi">{{ x.fullname }}</td>
                            </tr>
                            {% endfor %}
                        {% else %}
                            <p class="thick text-brown">You're the first!</p>
                        {% endif %}
                    </table>
                </div>
            </div>
            <a href="{% url 'regismember:regismember' %}"><input type="submit" value="Can't find your name?" action="{% url 'regismember:regismember' %}"></a>
        </div>
    </div>
</div>

{% endblock %}

RegisMember/templates/regismember.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/regisMember.css' %}" type="text/css">
</head>


<div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="roundedrec">
                    <div class="insiderec">
					{% if user.is_authenticated %}
					<h1 class="signed-in">You already signed in!</h1>
					<a href="{% url 'home' %}">
                                <p class="thick text-brown">Get to know what's <strong> trending</strong></p>
                                <br>
								</a>
					{% else %}
                            <p class="sign-up">Sign Up</p>
                            <form  method="POST" action="">
                                {% csrf_token %}
                                {% for field in form %}
                                    <p class="label_tag">{{ field.label_tag }} <br> {{ field }} </p> 
									<p class="label_tag">{{ field.errors }}</p> 
                                {% endfor %}
                                <input type="submit" id="submit" value="JOIN US" action="confirmationpage">
                            </form>
							<center>  
                            <br>
							<p class="label_tag">or</p>
							<div class="google" style="margin-bottom:20px">
							 <a href="{% url 'social:begin' 'google-oauth2' %}" style="text-transform:none">
								 <div class="left">
									 <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
								 </div>
								 <p class="label_tag1">Sign up with Google</p>
							 </a>
							</div> 
							<p class="label_tag1">Already have account? <a href="{% url 'login' %}">Sign in</a></p>            
							</center>
						{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

RegisMember/templates/transition.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/regisMember.css' %}" type="text/css">
</head>

        <div class="outside">
            <div class="insiderec">
                <h2 id="hold">Hold up!</h2><br>
                <p>You are not signed in. Sign in and enjoy the benefits!<br><br>
                    Here are the benefits of sign in : <br>
                    1. Book any event you want <br>
                    2. See your booking history <br>
                    3. Write on our comment section <br>
                    {% csrf_token %} 
                    <a href= "{% url 'login' %}"> <button id="labelBook" class="btn btn-default mini">Sign in</button></a><br><br>
                    Don't have an account?<br>
                    {% csrf_token %} 
                    <a href= "{% url 'regismember:regismember' %}"> <button id="labelBook" class="btn btn-default mini">Sign up</button></a><br>
                </p>
            </div>
        </div>

{% endblock %}