AllEvent/urls.py
from django.urls import path

from .views import Events, details, confirm
app_name= 'event'
urlpatterns = [
    path('', Events, name='event'),
    path('details/<event>/',details, name='details'),
    path('confirm/<event>/',confirm, name='confirm')
    
]

ListEvent/urls.py
from django.urls import path
from .views import profile
from django.conf import settings

app_name = 'eventList'
urlpatterns = [
	path('', profile, name = 'eventList')
]

RegisMember/urls.py
from django.urls import path
from . import views

app_name= 'regismember'
urlpatterns = [
    path('', views.RegisMemberView, name='regismember'),
    path('confirmationpage/', views.ConfirmationPageView, name='confirmationpage'),
    path('listmember/', views.listmember, name='listmember'),
    path('logout/', views.logout_view, name='logout'),
    path('validate/', views.checker, name='validate_mail'),
    path('loginPass/', views.loginPass, name='loginPass'),
    path('holdUp/', views.transition, name='transition'),
    path('confirmed/', views.bookconfirm, name='bookconfirm'),
]

TP1/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('event/', include('AllEvent.urls',namespace="event")),
    path('regismember/', include('RegisMember.urls', namespace="regismember")),
    path('bookform/', include('formBookEvent.urls',namespace="bookform")),
    path('news/', include('News.urls',namespace="news")),
    path('about/', include('About.urls', namespace="about")),
    path('', include('Home.urls')),
    path('bookformMember/', include('bookasMember.urls', namespace='bookformMember')),
	path('profileEvent/', include('ListEvent.urls', namespace='eventList'))
]

AllEvent/models.py
from django.db import models
from RegisMember.models import RegisMember

class Event(models.Model):
    name = models.CharField(max_length=50)
    pict = models.URLField(max_length=200)
    type_event= models.CharField(max_length=20)
    place= models.CharField(max_length=50)
    date = models.DateField()
    price= models.CharField(max_length=20)
    description=models.CharField(max_length=200)
    people = models.ManyToManyField(RegisMember, blank=True)

    def __str__(self):
        return self.name
# Create your models here.

ListEvent/models.py
from django.db import models

# Create your models here.

AllEvent/views.py
from django.shortcuts import render
from .models import Event

from formBookEvent.models import BookFormModels
from bookasMember.models import BookFormMemberModels
from django.http import HttpResponse
import json

response={}
def Events(request):
    education = Event.objects.all().filter(type_event='Education')
    entertainment= Event.objects.all().filter(type_event='Entertainment')
    response['education'] = education
    response['entertainment'] = entertainment
    return render (request, "listEvent.html", response)

def details(request, event=None):
    events= Event.objects.all().filter(name= event)
    response['event']=events[0]
    response['orang']= events[0].people.all()
    return render (request, 'eventDetails.html', response)

def confirm(request, event=None):
    events= Event.objects.all().filter(name= event)[0]
    user= request.user
    sudah=False
    if user in events.people.all():
        sudah=True
    else:
        events.people.add(user)    
    print(user.event_set.all())
    print(events.people.all())
    return HttpResponse(json.dumps({'items': user.username, 'sudah':sudah}))
    
    
    
    
# Create your views here.

ListEvent/views.py
from django.shortcuts import render, redirect
from AllEvent.models import Event

response={}
def profile(request):
	try:
		user = request.user
		event = user.event_set.all()
		response['nama'] = user.fullname
		response['username'] = user.username
		response['address'] = user.address
		response['event'] = event
		if(response['address'] == None ):
			response['address'] = "On Earth"
		return render(request, 'eventProfile.html', response)
	except AttributeError:
		return redirect("home")

AllEvent/templates/eventDetails.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<head>
<link rel="stylesheet" href="{% static 'css/eventDetails.css' %}" type="text/css">
</head>

<div class="container-fluid bg-3 text-center" style="margin-top:50px" id='details'>
		<div class="row">
			<div  class="col-sm col-md">
				<img class='image' src= {{ event.pict }}>
			</div>
			<div  class="col-sm col-md" style="margin-top:100px">
				<h1>{{ event.name }} </h1>
				{% if event.price == 'Coming Soon' %}
				<h5>{{ event.description }}</h5>
				{% else %}
				<h4>{{ event.date }}, in {{ event.place }}</h4>
				<h5>{{ event.description }}</h5>
				{% if user.is_authenticated %}
				<button onclick="join('{{ event.name }}')"  id="labelBookMember" class="btn btn-default">Book</button>
					{% else %}
						<a href="{% url 'regismember:transition' %}"><button id="labelBook" class="btn btn-default">Book</button> </a>
					{% endif %}
				{% endif %}
				<a href="{% url 'event:event' %}"> <button  id="labelBook" class="btn btn-default">See more</button> </a>
			</div>
		</div>
		{% if event.price == 'Coming Soon' %}
		{% else %}
		<div style='margin-top:100px'>
				<h3> Who's Coming?</h3>
				<div id="orang" class="table-responsive">
					<table class="table">
						{% for i in orang %}
						<td>
						{{i.username}}
						</td>
						{% endfor %}
						
					</table>
				</div>
		</div>
		{% endif %}
		<div id="modals" class="modal">You already book this event</div>
</div>
	

	

{% endblock %}

AllEvent/templates/listEvent.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<head>
<link rel="stylesheet" href="{% static 'css/eventDetails.css' %}" type="text/css">
</head>
<body>
	<div style='color:#6A5C55; margin-left:2vmax; margin-top:10px'>
		<h1><strong> Events</strong></h1>
		<h4> All the event you need</h4>
	</div>
	<h4 id='label' style="width:126px;padding-left:10px">education</h4>
	<div class="container-fluid bg-3 text-center ">
		<div class="row">
			{% for event in education %}
				<div  class="col-sm col-md">
					<a href="{% url 'event:details' event.name %}"> 
					<img id ='zoom' src= {{ event.pict }}  style ='width:280px; height:400px; '>
					<br>
					<button id='price'  class="btn btn-default">{{ event.price }}</button> 
					</a>
				</div>
			{% endfor %}
		</div>
	</div>
	
	
	<h4 id='label' style="width:178px; padding-left:10px" > entertainment</h4>
	<div class='container-fluid bg-3 text-center'>
		<div class="row">
			{% for event in entertainment %}
				<div class="col-md col-sm">
					<a href="{% url 'event:details' event.name %}">
					<img id ='zoom' src= {{ event.pict }} style ='width:280px; height:400px;'>
					<br>
					<button  id="price" class="btn btn-default">{{ event.price }}</button> 
					</a>
				</div>
			{% endfor %}
		</div>
	</div>
	<br>
</body>
{% endblock %}