About/urls.py
from django.urls import path
from .views import about, getComment

app_name= 'about'
urlpatterns = [
    path('', about, name='about'),
    path('getComment/', getComment)
]

AllEvent/urls.py
from django.urls import path

from .views import Events, details, confirm
app_name= 'event'
urlpatterns = [
    path('', Events, name='event'),
    path('details/<event>/',details, name='details'),
    path('confirm/<event>/',confirm, name='confirm')
    
]

ListEvent/urls.py
from django.urls import path
from .views import profile
from django.conf import settings

app_name = 'eventList'
urlpatterns = [
	path('', profile, name = 'eventList')
]

News/urls.py
from django.urls import path
from .views import News
app_name = 'news'

urlpatterns = [
	path('', News, name='news'),
]

TP1/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('event/', include('AllEvent.urls',namespace="event")),
    path('regismember/', include('RegisMember.urls', namespace="regismember")),
    path('bookform/', include('formBookEvent.urls',namespace="bookform")),
    path('news/', include('News.urls',namespace="news")),
    path('about/', include('About.urls', namespace="about")),
    path('', include('Home.urls')),
    path('bookformMember/', include('bookasMember.urls', namespace='bookformMember')),
	path('profileEvent/', include('ListEvent.urls', namespace='eventList'))
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Trending Inc.</title>
        <link rel="icon" href="{% static 'photos/t.png' %}" type="image/gif" sizes="16x16">
        <link rel="stylesheet" href="{% static 'css/csstrending.css' %}" type="text/css">
		<meta name="google-signin-client_id" content="793165754584-h9e13uhc75eg0n44drobf3m04rr2h5nt.apps.googleusercontent.com">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script src="https://apis.google.com/js/platform.js" async defer></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
		<script src="{% static 'js/script.js' %}"></script>
        <link href="https://fonts.googleapis.com/css?family=Nunito+Sans|Suez+One" rel="stylesheet">

    </head>
    <body>
        <!--NAVBAR-->
        <nav class="navbar navbar-expand-lg navbar-light">
                <a class="navbar-brand active" href="{% url 'home' %}"><img src="{% static 'photos/trending.png' %}" style="width:100px;"><span class="sr-only">(current)</span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item  events_news_font">
                            <a class="nav-link" href="{% url 'event:event' %}">Events</a>
                        </li>
                        <li class="nav-item  events_news_font" style="margin-right:8px">
                                <a class="nav-link" href="{% url 'news:news' %}">News</a>
                        </li >

						<li class="nav-item  events_news_font" style="margin-right:8px">
                                <a class="nav-link" href="{% url 'about:about' %}">About</a>
                        </li >
						{% if user.is_authenticated %}
						<li class="dropdown" style="margin-top:8px; margin-right: 10px;">
							<a class="dropdown-toggle" data-toggle="dropdown" >Hello, {{ user.username }}
							<span class="caret"></span></a>
							<ul class="dropdown-menu">
							{% csrf_token %} 
                            <li><a href="{% url 'eventList:eventList' %}" style="color: #6A5C55 !important; margin-left: 10px">My Profile</a></li>
							  <li><a href= "{% url 'regismember:logout' %}" style="color:#6A5C55 !important; margin-left:10px">Log Out</a></li>
							</ul>
						  </li>
						{% else %}
						<li class="dropdown" style="margin-top:10px; margin-right:10px">
							<a class="dropdown-toggle" data-toggle="dropdown" ><img src="{% static 'photos/Vector (1).png' %}" style="border-style:2px solid white; width:20px;">
							<span class="caret"></span></a>
							<ul class="dropdown-menu">
							{% csrf_token %} 

							  <li><a href= "{% url 'login' %}" style="color: #6A5C55 !important; margin-left:8px; font-size: 12px;">Sign in</a></li>
							  {% csrf_token %} 
							  <li><a href="{% url 'regismember:regismember' %}" style="color:#6A5C55 !important; margin-left:8px; font-size: 12px;">Sign up</a></li>
							</ul>
						  </li>
						
						{% endif %}
                    </ul>
                </div>
        </nav>

        {% block content %}
        {% endblock %}

    <!-- FOOTER -->
	<footer id="myFooter">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 img-responsive center text-center">
                        <a href = "#"><img class="socmed-logo" src="{% static 'photos/facebook.png' %}" hspace="20"></a>
                        <a href = "#"><img class="socmed-logo" src="{% static 'photos/twitter.png' %}"hspace="20"></a>
                        <a href = "#"><img class="socmed-logo" src="{% static 'photos/instagram.png' %}" hspace="20"></a>
                    <div class="col-sm-12 copyright">
                            <p>Copyright © 2018 Trending Inc. All rights reserved.<br>
                            First Assignment of Web Design and Programming Class F Group 11</p> 
                    </div>
                </div>
				</div>
            </div>
        </div>
    </footer>
    </body>
</html>